openapi: 3.0.1
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the docs for warp builds api for argonaut
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Warp Builds API Docs
  version: 0.4.0
servers:
- url: https://backend.warpbuild.com/api/v1
paths:
  /runner_instance:
    post:
      description: Add a new runner instance
      operationId: AddRunnerInstance
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/commons.AddRunnerInstanceInput'
        description: Add runner instance body
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commons.RunnerInstance'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarpBuildAPIError'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarpBuildAPIError'
          description: Not Found
      security:
      - WarpBuildServiceSecretAuth: []
      summary: Add a new runner instance
      tags:
      - v1 RunnerInstance
      x-codegen-request-body-name: body
  /runner_instance/{id}:
    delete:
      operationId: DeleteRunnerInstance
      parameters:
      - description: Runner Instance ID
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commons.Runner'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarpBuildAPIError'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarpBuildAPIError'
          description: Not Found
      security:
      - JWTKeyAuth: []
      summary: delete runner instance for the id. Current organization is figured
        from the authorization token
      tags:
      - v1 RunnerInstance
    get:
      operationId: GetRunnerInstance
      parameters:
      - description: Runner Instance ID
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commons.RunnerInstance'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarpBuildAPIError'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarpBuildAPIError'
          description: Not Found
      security:
      - JWTKeyAuth: []
      summary: Get runner instance by ID for the organization. Current organization
        is figured from the authorization token
      tags:
      - v1 RunnerInstance
  /runner_instance/{id}/telemetry:
    get:
      operationId: GetRunnerInstanceTelemetry
      parameters:
      - description: runner instance id
        in: path
        name: id
        required: true
        schema:
          type: string
      - description: "metric type (logs, metrics, or gha-logs)"
        in: query
        name: metric_type
        schema:
          enum:
          - logs
          - metrics
          - gha-logs
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commons.GetRunnerInstanceTelemetryOutput'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarpBuildAPIError'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarpBuildAPIError'
          description: Not Found
      security:
      - JWTKeyAuth: []
      summary: Gets metrics log files for a runner instance with presigned URLs
      tags:
      - v1 RunnerInstance
  /runner_instance/allocate:
    post:
      description: Allocate a runner instance
      operationId: AllocateRunnerInstance
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/commons.AllocateRunnerInstanceInput'
        description: Allocate runner instance body
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commons.RunnerInstance'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarpBuildAPIError'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarpBuildAPIError'
          description: Not Found
      summary: Allocate a runner instance
      tags:
      - v1 RunnerInstance
      x-codegen-request-body-name: body
  /runner_instance/internal/{id}/last_job_processed_meta:
    get:
      operationId: GetRunnerLastJobProcessedMeta
      parameters:
      - description: runner instance id
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commons.LastJobProcessedMeta'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarpBuildAPIError'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarpBuildAPIError'
          description: Not Found
      security:
      - WarpBuildServiceSecretAuth: []
      summary: Get runner last used job meta
      tags:
      - v1 RunnerInstance
  /runners_instance/{id}/allocation_details:
    get:
      operationId: GetRunnerInstanceAllocationDetails
      parameters:
      - description: runner instance id
        in: path
        name: id
        required: true
        schema:
          type: string
      - description: polling secret for validation
        in: header
        name: X-POLLING-SECRET
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commons.RunnerInstanceAllocationDetails'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarpBuildAPIError'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarpBuildAPIError'
          description: Not Found
      summary: Get runner instance allocation details for the id
      tags:
      - v1 RunnerInstance
  /runners_instance/{id}/cleanup_hook:
    post:
      operationId: RunnerInstanceCleanupHook
      parameters:
      - description: runner instance id
        in: path
        name: id
        required: true
        schema:
          type: string
      - description: polling secret for validation
        in: header
        name: X-POLLING-SECRET
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarpBuildAPIError'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarpBuildAPIError'
          description: Not Found
      summary: Get runner instance allocation details for the id
      tags:
      - v1 RunnerInstance
  /runners_instance/{id}/presigned_log_upload_url:
    get:
      operationId: GetRunnerInstancePresignedLogUploadURL
      parameters:
      - description: runner instance id
        in: path
        name: id
        required: true
        schema:
          type: string
      - description: polling secret for validation
        in: header
        name: X-POLLING-SECRET
        required: true
        schema:
          type: string
      - description: Log file name
        in: query
        name: log-file-name
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commons.GetPresignedLogUploadURLOutput'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarpBuildAPIError'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarpBuildAPIError'
          description: Not Found
      summary: Gets a presigned url for uploading logs for a runner instance
      tags:
      - v1 RunnerInstance
components:
  schemas:
    WarpBuildAPIError:
      properties:
        code:
          type: string
        description:
          type: string
        message:
          type: string
        sub_code:
          type: string
        sub_message:
          type: string
      type: object
    commons.AddRunnerInstanceInput:
      properties:
        dynamic_overrides:
          $ref: '#/components/schemas/commons.DynamicOverrides'
        provider_id:
          type: string
        runner_set_id:
          type: string
        unique_external_id:
          type: string
      type: object
    commons.AllocateRunnerInstanceInput:
      properties:
        allocation_requested_at:
          type: string
        allocation_requested_event_at:
          type: string
        labels:
          items:
            type: string
          type: array
        runner_for:
          type: string
        unique_external_id:
          type: string
        vcs_integration_id:
          type: string
      type: object
    commons.AttributeMap:
      additionalProperties: true
      type: object
    commons.ByocSku:
      example:
        instance_types:
        - instance_types
        - instance_types
        role_arn: role_arn
        network_tier: STANDARD
        is_public: true
        arch: arch
      properties:
        arch:
          type: string
        instance_types:
          items:
            type: string
          type: array
        is_public:
          type: boolean
        network_tier:
          description: |-
            NetworkTier is the network tier associated with the instance.
            This is only applicable for GCP based runners. Passing this for
            other providers will have no effect.

            Possible values:

            - PREMIUM: A premium network tier with fast network performance.

            - STANDARD: A standard network tier with basic features.

            Refer: https://cloud.google.com/network-tiers

            Default value is automatically picked if nothing is passed in case of GCP.

            +Default: STANDARD
          enum:
          - STANDARD
          - PREMIUM
          type: string
        role_arn:
          type: string
      type: object
    commons.DynamicOverrides:
      example:
        snapshot_key: snapshot_key
        configuration_overrides:
          capacity_type: spot
          image: image
          stock_runner_set_id: stock_runner_set_id
          byoc_sku:
            instance_types:
            - instance_types
            - instance_types
            role_arn: role_arn
            network_tier: STANDARD
            is_public: true
            arch: arch
          storage:
            performance_tier: P15
            size: 9
            tier: low
            disk_type: pd-balanced
            iops: 7
            throughput: 3
          sku:
            cores: 0
            memory: 6
            os:
            - mac
            - mac
            arch: x64
            id: id
            display_name: display_name
            properties:
              generation: generation
              burstable_speed: 1.4658129805029452
              performance_category: small
              performance_rating: 5
              gpu: 5
              speed: 2.3021358869347655
              manufacturer: any
      properties:
        configuration_overrides:
          $ref: '#/components/schemas/commons.RunnerInstanceConfiguration'
        snapshot_key:
          type: string
      type: object
    commons.GetPresignedLogUploadURLOutput:
      example:
        url: url
      properties:
        url:
          type: string
      type: object
    commons.GetRunnerInstanceTelemetryOutput:
      example:
        telemetry_files:
        - file_name: file_name
          presigned_url: presigned_url
          timestamp: timestamp
        - file_name: file_name
          presigned_url: presigned_url
          timestamp: timestamp
      properties:
        telemetry_files:
          items:
            $ref: '#/components/schemas/commons.TelemetryLogFile'
          type: array
      type: object
    commons.GithubRunnerApplicationDetails:
      example:
        variables:
          key: variables
        jit: jit
        runner_name: runner_name
        labels:
        - labels
        - labels
      properties:
        jit:
          type: string
        labels:
          items:
            type: string
          type: array
        runner_name:
          type: string
        variables:
          additionalProperties:
            type: string
          type: object
      type: object
    commons.InstanceSku:
      example:
        cores: 0
        memory: 6
        os:
        - mac
        - mac
        arch: x64
        id: id
        display_name: display_name
        properties:
          generation: generation
          burstable_speed: 1.4658129805029452
          performance_category: small
          performance_rating: 5
          gpu: 5
          speed: 2.3021358869347655
          manufacturer: any
      properties:
        arch:
          enum:
          - x64
          - arm64
          type: string
        cores:
          type: integer
        display_name:
          type: string
        id:
          type: string
        memory:
          type: integer
        os:
          items:
            enum:
            - mac
            - ubuntu
            type: string
          type: array
        properties:
          $ref: '#/components/schemas/commons.InstanceSkuProperties'
      type: object
    commons.InstanceSkuProperties:
      example:
        generation: generation
        burstable_speed: 1.4658129805029452
        performance_category: small
        performance_rating: 5
        gpu: 5
        speed: 2.3021358869347655
        manufacturer: any
      properties:
        burstable_speed:
          type: number
        generation:
          type: string
        gpu:
          type: integer
        manufacturer:
          enum:
          - any
          - amd
          - intel
          - arm
          type: string
        performance_category:
          enum:
          - small
          - medium
          - large
          type: string
        performance_rating:
          type: integer
        speed:
          type: number
      type: object
    commons.LabelAttribute:
      example:
        attributes:
          key: ""
        runner: runner
      properties:
        attributes:
          additionalProperties: true
          type: object
        runner:
          type: string
      type: object
    commons.LabelAttributes:
      example:
        parsed_labels:
        - parsed_labels
        - parsed_labels
        attributes_arr:
        - attributes:
            key: ""
          runner: runner
        - attributes:
            key: ""
          runner: runner
      properties:
        attributes_arr:
          items:
            $ref: '#/components/schemas/commons.LabelAttribute'
          type: array
        parsed_labels:
          items:
            type: string
          type: array
      type: object
    commons.LastJobProcessedMeta:
      example:
        vcs_base_ref: vcs_base_ref
        vcs_default_branch: vcs_default_branch
        vcs_head_ref: vcs_head_ref
        vcs_job_name: vcs_job_name
        vcs_end_time: vcs_end_time
        vcs_ref: vcs_ref
        vcs_workflow_group_id: vcs_workflow_group_id
        vcs_org: vcs_org
        vcs_repo: vcs_repo
        vcs_commit_message: vcs_commit_message
        vcs_ref_type: vcs_ref_type
        vcs_start_time: vcs_start_time
      properties:
        vcs_base_ref:
          type: string
        vcs_commit_message:
          type: string
        vcs_default_branch:
          type: string
        vcs_end_time:
          type: string
        vcs_head_ref:
          type: string
        vcs_job_name:
          type: string
        vcs_org:
          type: string
        vcs_ref:
          type: string
        vcs_ref_type:
          type: string
        vcs_repo:
          type: string
        vcs_start_time:
          type: string
        vcs_workflow_group_id:
          type: string
      type: object
    commons.Runner:
      example:
        updated_at: updated_at
        configuration:
          capacity_type: spot
          image: image
          byoc_sku:
            instance_types:
            - instance_types
            - instance_types
            role_arn: role_arn
            network_tier: STANDARD
            is_public: true
            arch: arch
          storage:
            performance_tier: P15
            size: 9
            tier: low
            disk_type: pd-balanced
            iops: 7
            throughput: 3
          sku: sku
        stock_runner_id: stock_runner_id
        meta:
          supports_snapshot: true
        organization_id: organization_id
        name: name
        vcs_integration_id: vcs_integration_id
        active: true
        created_at: created_at
        provider_id: provider_id
        id: id
        labels:
        - labels
        - labels
      properties:
        active:
          type: boolean
        configuration:
          $ref: '#/components/schemas/commons.RunnerSetConfiguration'
        created_at:
          type: string
        id:
          type: string
        labels:
          items:
            type: string
          type: array
        meta:
          $ref: '#/components/schemas/commons.SetMeta'
        name:
          type: string
        organization_id:
          type: string
        provider_id:
          type: string
        stock_runner_id:
          description: LabelOverrides   *LabelAttributes        `json:"label_overrides"`
          type: string
        updated_at:
          type: string
        vcs_integration_id:
          type: string
      type: object
    commons.RunnerInstance:
      example:
        cluster: cluster
        label_attributes:
          parsed_labels:
          - parsed_labels
          - parsed_labels
          attributes_arr:
          - attributes:
              key: ""
            runner: runner
          - attributes:
              key: ""
            runner: runner
        running_started_at: running_started_at
        last_job_processed_id: last_job_processed_id
        configuration:
          capacity_type: spot
          image: image
          stock_runner_set_id: stock_runner_set_id
          byoc_sku:
            instance_types:
            - instance_types
            - instance_types
            role_arn: role_arn
            network_tier: STANDARD
            is_public: true
            arch: arch
          storage:
            performance_tier: P15
            size: 9
            tier: low
            disk_type: pd-balanced
            iops: 7
            throughput: 3
          sku:
            cores: 0
            memory: 6
            os:
            - mac
            - mac
            arch: x64
            id: id
            display_name: display_name
            properties:
              generation: generation
              burstable_speed: 1.4658129805029452
              performance_category: small
              performance_rating: 5
              gpu: 5
              speed: 2.3021358869347655
              manufacturer: any
        allocation_requested_at: allocation_requested_at
        created_at: created_at
        external_id: external_id
        first_polled_at: first_polled_at
        runner_for: runner_for
        runner_set_id: runner_set_id
        updated_at: updated_at
        host: host
        vcs_integration_id: vcs_integration_id
        id: id
        allocation_requested_event_at: allocation_requested_event_at
        allocated_at: allocated_at
        dynamic_overrides:
          snapshot_key: snapshot_key
          configuration_overrides:
            capacity_type: spot
            image: image
            stock_runner_set_id: stock_runner_set_id
            byoc_sku:
              instance_types:
              - instance_types
              - instance_types
              role_arn: role_arn
              network_tier: STANDARD
              is_public: true
              arch: arch
            storage:
              performance_tier: P15
              size: 9
              tier: low
              disk_type: pd-balanced
              iops: 7
              throughput: 3
            sku:
              cores: 0
              memory: 6
              os:
              - mac
              - mac
              arch: x64
              id: id
              display_name: display_name
              properties:
                generation: generation
                burstable_speed: 1.4658129805029452
                performance_category: small
                performance_rating: 5
                gpu: 5
                speed: 2.3021358869347655
                manufacturer: any
        last_polled_at: last_polled_at
        allocation_mutex_timeout: allocation_mutex_timeout
        created_by: created_by
        last_job_processed_meta:
          vcs_base_ref: vcs_base_ref
          vcs_default_branch: vcs_default_branch
          vcs_head_ref: vcs_head_ref
          vcs_job_name: vcs_job_name
          vcs_end_time: vcs_end_time
          vcs_ref: vcs_ref
          vcs_workflow_group_id: vcs_workflow_group_id
          vcs_org: vcs_org
          vcs_repo: vcs_repo
          vcs_commit_message: vcs_commit_message
          vcs_ref_type: vcs_ref_type
          vcs_start_time: vcs_start_time
        labels:
        - labels
        - labels
        allocation_for: allocation_for
        post_resume_first_polled_at: post_resume_first_polled_at
        stack_kind: stack_kind
        organization_id: organization_id
        provider_kind_id: provider_kind_id
        purged_at: purged_at
        purged_reason: purged_reason
        suspending_started_at: suspending_started_at
        status: status
        suspended_at: suspended_at
      properties:
        allocated_at:
          type: string
        allocation_for:
          type: string
        allocation_mutex_timeout:
          type: string
        allocation_requested_at:
          type: string
        allocation_requested_event_at:
          type: string
        cluster:
          type: string
        configuration:
          $ref: '#/components/schemas/commons.RunnerInstanceConfiguration'
        created_at:
          type: string
        created_by:
          type: string
        dynamic_overrides:
          $ref: '#/components/schemas/commons.DynamicOverrides'
        external_id:
          type: string
        first_polled_at:
          type: string
        host:
          type: string
        id:
          type: string
        label_attributes:
          $ref: '#/components/schemas/commons.LabelAttributes'
        labels:
          items:
            type: string
          type: array
        last_job_processed_id:
          type: string
        last_job_processed_meta:
          $ref: '#/components/schemas/commons.LastJobProcessedMeta'
        last_polled_at:
          type: string
        organization_id:
          type: string
        post_resume_first_polled_at:
          type: string
        provider_kind_id:
          type: string
        purged_at:
          type: string
        purged_reason:
          type: string
        runner_for:
          type: string
        runner_set_id:
          type: string
        running_started_at:
          type: string
        stack_kind:
          type: string
        status:
          type: string
        suspended_at:
          type: string
        suspending_started_at:
          type: string
        updated_at:
          type: string
        vcs_integration_id:
          type: string
      type: object
    commons.RunnerInstanceAllocationDetails:
      example:
        gh_runner_application_details:
          variables:
            key: variables
          jit: jit
          runner_name: runner_name
          labels:
          - labels
          - labels
        runner_application: github
        telemetry_enabled: true
        runner_instance:
          cluster: cluster
          label_attributes:
            parsed_labels:
            - parsed_labels
            - parsed_labels
            attributes_arr:
            - attributes:
                key: ""
              runner: runner
            - attributes:
                key: ""
              runner: runner
          running_started_at: running_started_at
          last_job_processed_id: last_job_processed_id
          configuration:
            capacity_type: spot
            image: image
            stock_runner_set_id: stock_runner_set_id
            byoc_sku:
              instance_types:
              - instance_types
              - instance_types
              role_arn: role_arn
              network_tier: STANDARD
              is_public: true
              arch: arch
            storage:
              performance_tier: P15
              size: 9
              tier: low
              disk_type: pd-balanced
              iops: 7
              throughput: 3
            sku:
              cores: 0
              memory: 6
              os:
              - mac
              - mac
              arch: x64
              id: id
              display_name: display_name
              properties:
                generation: generation
                burstable_speed: 1.4658129805029452
                performance_category: small
                performance_rating: 5
                gpu: 5
                speed: 2.3021358869347655
                manufacturer: any
          allocation_requested_at: allocation_requested_at
          created_at: created_at
          external_id: external_id
          first_polled_at: first_polled_at
          runner_for: runner_for
          runner_set_id: runner_set_id
          updated_at: updated_at
          host: host
          vcs_integration_id: vcs_integration_id
          id: id
          allocation_requested_event_at: allocation_requested_event_at
          allocated_at: allocated_at
          dynamic_overrides:
            snapshot_key: snapshot_key
            configuration_overrides:
              capacity_type: spot
              image: image
              stock_runner_set_id: stock_runner_set_id
              byoc_sku:
                instance_types:
                - instance_types
                - instance_types
                role_arn: role_arn
                network_tier: STANDARD
                is_public: true
                arch: arch
              storage:
                performance_tier: P15
                size: 9
                tier: low
                disk_type: pd-balanced
                iops: 7
                throughput: 3
              sku:
                cores: 0
                memory: 6
                os:
                - mac
                - mac
                arch: x64
                id: id
                display_name: display_name
                properties:
                  generation: generation
                  burstable_speed: 1.4658129805029452
                  performance_category: small
                  performance_rating: 5
                  gpu: 5
                  speed: 2.3021358869347655
                  manufacturer: any
          last_polled_at: last_polled_at
          allocation_mutex_timeout: allocation_mutex_timeout
          created_by: created_by
          last_job_processed_meta:
            vcs_base_ref: vcs_base_ref
            vcs_default_branch: vcs_default_branch
            vcs_head_ref: vcs_head_ref
            vcs_job_name: vcs_job_name
            vcs_end_time: vcs_end_time
            vcs_ref: vcs_ref
            vcs_workflow_group_id: vcs_workflow_group_id
            vcs_org: vcs_org
            vcs_repo: vcs_repo
            vcs_commit_message: vcs_commit_message
            vcs_ref_type: vcs_ref_type
            vcs_start_time: vcs_start_time
          labels:
          - labels
          - labels
          allocation_for: allocation_for
          post_resume_first_polled_at: post_resume_first_polled_at
          stack_kind: stack_kind
          organization_id: organization_id
          provider_kind_id: provider_kind_id
          purged_at: purged_at
          purged_reason: purged_reason
          suspending_started_at: suspending_started_at
          status: status
          suspended_at: suspended_at
        status: unassigned
      properties:
        gh_runner_application_details:
          $ref: '#/components/schemas/commons.GithubRunnerApplicationDetails'
        runner_application:
          enum:
          - github
          type: string
        runner_instance:
          $ref: '#/components/schemas/commons.RunnerInstance'
        status:
          enum:
          - unassigned
          - assigned
          - invalidated
          type: string
        telemetry_enabled:
          type: boolean
      type: object
    commons.RunnerInstanceConfiguration:
      example:
        capacity_type: spot
        image: image
        stock_runner_set_id: stock_runner_set_id
        byoc_sku:
          instance_types:
          - instance_types
          - instance_types
          role_arn: role_arn
          network_tier: STANDARD
          is_public: true
          arch: arch
        storage:
          performance_tier: P15
          size: 9
          tier: low
          disk_type: pd-balanced
          iops: 7
          throughput: 3
        sku:
          cores: 0
          memory: 6
          os:
          - mac
          - mac
          arch: x64
          id: id
          display_name: display_name
          properties:
            generation: generation
            burstable_speed: 1.4658129805029452
            performance_category: small
            performance_rating: 5
            gpu: 5
            speed: 2.3021358869347655
            manufacturer: any
      properties:
        byoc_sku:
          $ref: '#/components/schemas/commons.ByocSku'
        capacity_type:
          enum:
          - spot
          - ondemand
          type: string
        image:
          type: string
        sku:
          $ref: '#/components/schemas/commons.InstanceSku'
        stock_runner_set_id:
          type: string
        storage:
          $ref: '#/components/schemas/commons.Storage'
      type: object
    commons.RunnerSetConfiguration:
      example:
        capacity_type: spot
        image: image
        byoc_sku:
          instance_types:
          - instance_types
          - instance_types
          role_arn: role_arn
          network_tier: STANDARD
          is_public: true
          arch: arch
        storage:
          performance_tier: P15
          size: 9
          tier: low
          disk_type: pd-balanced
          iops: 7
          throughput: 3
        sku: sku
      properties:
        byoc_sku:
          $ref: '#/components/schemas/commons.ByocSku'
        capacity_type:
          enum:
          - spot
          - ondemand
          type: string
        image:
          type: string
        sku:
          type: string
        storage:
          $ref: '#/components/schemas/commons.Storage'
      type: object
    commons.SetMeta:
      example:
        supports_snapshot: true
      properties:
        supports_snapshot:
          type: boolean
      type: object
    commons.Storage:
      example:
        performance_tier: P15
        size: 9
        tier: low
        disk_type: pd-balanced
        iops: 7
        throughput: 3
      properties:
        disk_type:
          description: |-
            DiskType is the disk type associated with the instance.

            This is only applicable for GCP based runners for now. Passing this for
            other providers will have no effect.

            Possible values:

            - pd-standard: Standard persistent disk.

            - pd-ssd: SSD persistent disk.

            - pd-balanced: Balanced persistent disk.

            - pd-extreme: Extreme persistent disk. (to be added later)

            - hyperdisk-balanced: Hyperdisk balanced persistent disk.

            - hyperdisk-extreme: Hyperdisk extreme persistent disk.

            Refer: https://cloud.google.com/compute/docs/disks#disk-types

            Default value is automatically picked if nothing is passed in case of GCP.

            +Default: pd-ssd
          enum:
          - pd-balanced
          - pd-standard
          - pd-ssd
          - hyperdisk-balanced
          - hyperdisk-extreme
          type: string
        iops:
          description: |-
            IOPS is the IOPS of the storage.

            For GCP,
            This is not applicable.
            Any passed value will be ignored.
          type: integer
        performance_tier:
          description: |-
            PerformanceTier is the provider specific performance tier of the storage.
            This is applicable for Azure as of now, can be extended to other providers in the future.
            Passing this for other providers will have no effect.

            Refer: https://learn.microsoft.com/en-us/azure/virtual-machines/disks-change-performance

            Possible values:

            - P15
            - P20
            - P30
            - P40
            - P50

            Default value is automatically picked if nothing is passed in case of Azure.

            +Default: P15
          enum:
          - P15
          - P20
          - P30
          - P40
          - P50
          type: string
        size:
          type: integer
        throughput:
          description: |-
            Throughput is the throughput of the storage.

            For GCP,
            This is not applicable.
            Any passed value will be ignored.
          type: integer
        tier:
          description: |-
            Tier is the tier of the storage.

            If GCP based, you must set this to custom.
          enum:
          - low
          - medium
          - high
          - extreme
          - custom
          type: string
      type: object
    commons.TelemetryLogFile:
      example:
        file_name: file_name
        presigned_url: presigned_url
        timestamp: timestamp
      properties:
        file_name:
          type: string
        presigned_url:
          type: string
        timestamp:
          type: string
      type: object
x-extension-openapi:
  example: value on a json format
x-original-swagger-version: "2.0"
